export const COMMON_PAGEINIT_SUCCESS = 'COMMON_PAGEINIT_SUCCESS'
export const LIST_LOAD_MERCHANTINFO_SUCCESS = 'LIST_LOAD_MERCHANTINFO_SUCCESS'
export const LIST_SUBMIT_MERCHANTINFO_SUCCESS = 'LIST_SUBMIT_MERCHANTINFO_SUCCESS'
