version: v1
common:
    tools:
        node: 8.11.1     # 环境工具 白名单，版本号可为空，代表最新版本
        git:                         # 有些npm包会使用git clone其他包代码
build:
    cache:
        dirs:
            - node_modules
    run:
        cmd:
            - deploy/server/pre/staging
    target:
        files:
            - ./*

deploy:
    tools:
        node: 8.11.1     # 环境工具 白名单，版本号可为空，代表最新版本

    targetDir: /opt/meituan/fe-scm-merchant

    run:
        workDir: /opt/meituan/fe-scm-merchant # 执行cmd的目录
        cmd:
            - deploy/server/post/staging
            - bash                   # 非常重要，否则如果在上一句执行出错，会导致容器异常退出，无法登陆查看日志的情况
            